name: Upload CSV to OSF

on:
  push:
    paths:
      - "ariadne/data/data_ariadne_nodes.csv"
    branches:
      - master
  workflow_dispatch:

jobs:
  process_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install pandas openpyxl && pip install osfclient

      - name: Process CSV and create XLSX
        env:
          OSF_TOKEN: ${{ secrets.OSF_TOKEN }}
          OSF_USERNAME: caggursoy
          OSF_PROJECT: tqjh8
        # run: python autoConv/autoConv.py && osf remove "2023 ARIADNE/ARIADNE Resources.xlsx" && osf upload ARIADNE_Resources.xlsx "2023 ARIADNE/ARIADNE Resources.xlsx"
        run: python autoConv/autoConv.py
